### ISSUE TITLE
"Installation Aborted" no matter what I do.

### ISSUE THREAD

**Issue by mrwallace888** [ow-mods/ow-mod-manager#171]
Every time the mod manager updates I can never update it in the manager. But here's the thing, I can't even install anything using the installer either.

Here's a video showing what happens. I both told it to install in the same directory but even if I try to reinstall in a different directory, no dice.

https://user-images.githubusercontent.com/39398330/187044011-54a18f2a-9834-456a-8133-0ea83a044a3a.mp4

(When the screen goes black automatically, that's from the UAC. I'm telling it "Yes".

**Comment by ImNitro** [comment]
Necro, but did you fix this Having the same issue.

**Comment by MegaPiggy** [comment]
https://github.com/ow-mods/ow-mod-manager#installation-aborted-error

**Comment by ImNitro** [comment]
> https://github.com/ow-mods/ow-mod-manager#installation-aborted-error

Thanks, fixed already by using the standalone exe version.
