### ISSUE TITLE
Characters like ö in filenames turning into � when installing mod

### ISSUE THREAD

**Issue by dgarroDC** [ow-mods/ow-mod-manager#174]
If I manually download and extract a mod zip that has characters like ö in filenames, they don't have issues (left in the example image), but if I install that mod with the mod manager, the ö are turned into � (right in the example image).

Mod example: https://github.com/FixxionsLair/Secret-Words/releases/download/0.1.2/Fixxion.SecretWords.zip

Result:
![image](https://user-images.githubusercontent.com/22490080/189261180-a7e2e6f1-895e-4cac-b084-652cd71f6a24.png)

**Comment by Raicuparta** [comment]
The solution is to not use those characters in file names. The problem is likely in the unzip library.
