### ISSUE TITLE
Mod manager can't find game

### ISSUE THREAD

**Issue by Pip0i** [ow-mods/ow-mod-manager#186]
i wanted to play the VR-Mod for OW.
I've purchased OW on Epic Game Launcher.
I installed the mod manager, OWML and NomaiVR.

But when I press Start Game, this is whats displayed in the logs:
 

Client connected to console | Mod Manager |  
Started OWML v2.9.0 | OWML |  
Current game path is not valid: F:/Epic/Games/TheOuterWorlds | OWML |  
Game not found in Steam. | OWML |  
Game not found in EGS. | OWML |  
Game not found in UWP. | OWML |  
Game not found in default locations. | OWML |  
Game not found at F:/Epic/Games/TheOuterWorlds | OWML |  
Please enter the correct game path: | OWML

The gamepath is correct and i also tried to start with "launch game exe directly" enablled. 
I can start the game all normally threew epic game launcher.

**Comment by Raicuparta** [comment]
Go to the manager settings and insert the correct game path here:
![image](https://user-images.githubusercontent.com/3955124/216351194-9bd70a29-3bea-402a-a76a-433ea9003c00.png)

If that doesn't work, you can also insert the game path in the black console window that pops up when you try running the game from the manager.

**Comment by MegaPiggy** [comment]
Are you sure you have the right game? The Outer Worlds is different from Outer Wilds.

**Comment by Raicuparta** [comment]
lol didn't even notice
